### ISSUE TITLE
Exception while running Discovery

### ISSUE THREAD

**Issue by guyluz11** [Butzlabben/upnp.dart#10]
```dart
/home/myUser/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --enable-asserts /home/myUser/Documents/git/network_tools/network_tools/example/test.dart
ERROR: FormatException: ERROR: Failed to parse device description. XmlParserException: Expected a single root element at 1:10 - http://192.168.31.237:9080
#0      DiscoveredClient.getDevice (package:upnp2/src/discovery.dart:376:7)
<asynchronous suspension>
#1      main.<anonymous closure> (file:///home/myUser/Documents/git/network_tools/network_tools/example/test.dart:9:19)
<asynchronous suspension>
```

Example code that I used 

```dart
import 'package:upnp2/upnp.dart';

// NOTE: Open the example directory to see more elaborate examples
main() async {
  final disc = DeviceDiscoverer();
  await disc.start(ipv6: false);
  disc.quickDiscoverClients().listen((client) async {
    try {
      final dev = await client.getDevice();
      print('Found device: ${dev!.friendlyName}: ${dev.url}');
    } catch (e, stack) {
      print('ERROR: $e - ${client.location}');
      print(stack);
    }
  });
}

```

Debugged the response in discovery.dart file line 372 and the value of the content variable is `status=ok`

This IP belongs to my LGwebOSTV

**Comment by daniel-naegele** [comment]
It seems, that the XML send back from the device has some formatting errors, could you maybe provide the output http://192.168.31.237:9080 ? Or debug the issue and look what the response returned from the device is?

**Comment by guyluz11** [comment]
The response from the device is `status=ok`

![image](https://user-images.githubusercontent.com/9304740/215165770-c5e287fc-612c-4cd0-90a8-3c14910c4cb0.png)

**Comment by daniel-naegele** [comment]
I need the body (see Response tab when inspecting a request) of the message, maybe you could paste it here

**Comment by guyluz11** [comment]
We'll test it again at the end of the week when I will get back to the same WiFi

**Comment by guyluz11** [comment]
Ha ha, 
as expected it is the same
![image](https://user-images.githubusercontent.com/9304740/216450497-8662c9c4-d186-4082-85ac-227fcbbdf1b6.png)

**Comment by daniel-naegele** [comment]
What kind of device is this? This does not seem to be in accordance with the UPnP specification

**Comment by guyluz11** [comment]
Smart TV made by LG.
it is like android tv but is not android at all, and operating system called webos

https://en.m.wikipedia.org/wiki/WebOS
